[package]
name = "tyt"
version = "0.1.0"
authors = ["joooscha <joscha.loos@pm.me>"]
edition = "2018"

[dependencies]
termion = "*"
tui = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
quick-xml = { version = "*", features = ["serialize"] }
reqwest = { version = "*", features = ["blocking"] }
regex = "*"
toml = "*"
chrono = "*"
