[package]
name = "tyt"
version = "0.10.0"
authors = ["joooscha <joscha.loos@pm.me>"]
edition = "2018"

[dependencies]
termion = "*"
tui = "*"
clipboard = "*"
rand = "*"

data = { path = "./data" }
feed_types = { path = "./feed_types" }
notification = { path = "./notification" }
