[package]
name = "tyt"
version = "1.0.0"
authors = ["joooscha <j.loos@posteo.net>"]
edition = "2018"

[dependencies]
termion = "*"
tui = "*"
clipboard = "*"

notification = { path = "./notification" }
core = { path = "./core" }
