[package]
name = "tyt"
version = "0.6.9"
authors = ["joooscha <joscha.loos@pm.me>"]
edition = "2018"

[dependencies]
termion = "*"
tui = "*"
clipboard = "*"

data = { path = "./data" }
data_types = { path = "./data_types" }
