[package]
name = "tyt"
version = "0.10.0"
authors = ["joooscha <j.loos@posteo.net>"]
edition = "2018"

[dependencies]
termion = "*"
tui = "*"
clipboard = "*"
# rand = "*"

# data = { path = "./data" }
notification = { path = "./notification" }
app = { path = "./app" }
