[package]
name = "data_types"
version = "0.1.7"
authors = ["joooscha <joscha.loos@pm.me>"]
edition = "2018"

[dependencies]
serde = { version = "*", features = ["derive"] }
serde_json = "*"
quick-xml = { version = "*", features = ["serialize"] }
tui = "*"
chrono = "*"
